version: '2'

services:
  ui:
    tty: true # Enables debugging capabilities when attached to this container.
    build: ./docker
    depends_on:
      - api
      - ratesvc
    ports:
      - 4200:4200
    volumes:
      - .:/app
    command: "ng serve --host 0.0.0.0 --proxy-config proxy.conf.json"
  api:
    tty: true
    image: bitnami/monocular-api:latest
    depends_on:
      - mongodb
    volumes:
      - ./docs/config.example.yaml:/root/monocular/config/monocular.yaml
      # Used for loading kubernetes context used on Helm releases integration
      - $HOME/.kube/:/root/.kube
      - monocular-data:/root/monocular
    environment:
      - ENVIRONMENT=development
      - MONOCULAR_AUTH_SIGNING_KEY=secret
    command:
    - monocular
    - --mongo-url=mongodb://root:password123@mongodb
  ratesvc:
    image: kubeapps/ratesvc:latest
    depends_on:
      - mongodb
    environment:
    - JWT_KEY=secret
    command:
    - /ratesvc
    - --mongo-url=mongodb://root:password123@mongodb
    - --mongo-database=ratesvc
  mongodb:
    image: bitnami/mongodb:3
    environment:
      - MONGODB_ROOT_PASSWORD=password123
  auth:
    image: kubeapps/oauth2-bitnami:latest
    depends_on:
      - mongodb
    command:
    - /oauth2-bitnami
    - --jwt-key=secret
    - --client-id=$AUTH_CLIENT_ID
    - --client-secret=$AUTH_CLIENT_SECRET
    - --mongo-url=mongodb://root:password123@mongodb
    - --mongo-database=users
    environment:
    - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
    - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
    - AUTH_SIGNING_KEY=secret
volumes:
  monocular-data:
